spring:
 cloud:
  gateway:
    routes:
      - id: customers
        uri: http://localhost:8082/
        predicates:
          - Path=/customers/**,/customer/**
      - id: accounts
        uri: http://localhost:8092/
        predicates:
          - Path=/accounts/**,/account/**